/* =============================================================
   MockupAI — CodeGenerator.js
   Converts AI JSON data → clean HTML5 + CSS3 + JS
   ============================================================= */

const CodeGenerator = {

  generate(data) {
    const css  = this.generateCSS(data);
    const js   = this.generateJS();
    const html = this.generateHTML(data, css, js);
    return { html, css, js };
  },

  /* ----------------------------------------------------------
     CSS — spacing scale, fluid type, mobile nav, card system
  ---------------------------------------------------------- */
  generateCSS(data) {
    const p = data.colorPalette || {};
    const primary   = p.primary   || '#6366f1';
    const secondary = p.secondary || '#818cf8';
    const accent    = p.accent    || '#f59e0b';
    const dark      = p.dark      || '#0d1117';
    const light     = p.light     || '#f5f7ff';
    const headingFont = (data.typography?.heading || 'Inter').replace(/['"]/g, '');
    const bodyFont    = (data.typography?.body    || 'Inter').replace(/['"]/g, '');

    return `/* =============================================
   Generated by MockupAI — ${data.businessName}
   ============================================= */

/* ---- Design Tokens ---- */
:root {
  /* Brand Colors */
  --primary:       ${primary};
  --secondary:     ${secondary};
  --accent:        ${accent};
  --dark:          ${dark};
  --light:         ${light};
  /* Spacing Scale */
  --space-xs:  8px;
  --space-sm:  16px;
  --space-md:  24px;
  --space-lg:  48px;
  --space-xl:  80px;
  --space-2xl: 120px;
  /* Typography */
  --font-heading: '${headingFont}', system-ui, sans-serif;
  --font-body:    '${bodyFont}', system-ui, sans-serif;
  /* Shape */
  --radius:    12px;
  --radius-lg: 20px;
  --radius-xl: 32px;
  /* Elevation */
  --shadow:    0 2px 8px rgba(0,0,0,0.06), 0 4px 20px rgba(0,0,0,0.06);
  --shadow-lg: 0 8px 32px rgba(0,0,0,0.10), 0 20px 56px rgba(0,0,0,0.08);
  --shadow-xl: 0 24px 72px rgba(0,0,0,0.16);
  /* Layout */
  --max-width: 1200px;
  /* Motion */
  --ease: 0.22s ease;
  --ease-slow: 0.4s ease;
}

/* ---- Reset ---- */
*, *::before, *::after {
  box-sizing: border-box;
  margin: 0;
  padding: 0;
  min-width: 0;
}
html { scroll-behavior: smooth; overflow-x: hidden; }
body {
  font-family: var(--font-body);
  font-size: clamp(0.9375rem, 1.5vw, 1.0625rem);
  line-height: 1.65;
  color: #0f172a;
  background: #fff;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  overflow-x: hidden;
  width: 100%;
  overflow-wrap: break-word;
  word-break: break-word;
}
img {
  max-width: 100%;
  width: 100%;
  height: auto;
  display: block;
  object-fit: cover;
}
a { text-decoration: none; color: inherit; }
ul { list-style: none; }
button { font-family: inherit; border: none; cursor: pointer; }

/* ---- Fluid Headings ---- */
h1 {
  font-family: var(--font-heading);
  font-size: clamp(2.25rem, 5vw, 4.5rem);
  font-weight: 800;
  line-height: 1.06;
  letter-spacing: -1.5px;
}
h2 {
  font-family: var(--font-heading);
  font-size: clamp(1.75rem, 4vw, 3rem);
  font-weight: 800;
  line-height: 1.12;
  letter-spacing: -0.5px;
}
h3 {
  font-family: var(--font-heading);
  font-size: clamp(1rem, 2vw, 1.2rem);
  font-weight: 700;
  line-height: 1.3;
}

/* ---- Layout Utilities ---- */
.container {
  max-width: var(--max-width);
  margin: 0 auto;
  padding: 0 var(--space-md);
}
.section-header {
  text-align: center;
  margin-bottom: var(--space-lg);
  max-width: 660px;
  margin-inline: auto;
  margin-bottom: var(--space-lg);
}
.section-label {
  display: inline-block;
  font-size: 0.7rem;
  font-weight: 700;
  text-transform: uppercase;
  letter-spacing: 0.14em;
  color: var(--primary);
  margin-bottom: var(--space-sm);
}
.section-heading {
  font-family: var(--font-heading);
  font-size: clamp(1.75rem, 4vw, 2.75rem);
  font-weight: 800;
  color: #0f172a;
  line-height: 1.14;
  margin-bottom: 12px;
}
.section-sub {
  color: #64748b;
  font-size: 1.0rem;
  max-width: 540px;
  margin-inline: auto;
  line-height: 1.75;
}

/* ---- Button System ---- */
.btn {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  gap: 8px;
  padding: 14px 28px;
  border-radius: 10px;
  font-weight: 700;
  font-size: 0.9375rem;
  cursor: pointer;
  border: 2px solid transparent;
  transition: background var(--ease), color var(--ease), opacity var(--ease),
              transform var(--ease), box-shadow var(--ease), border-color var(--ease);
  text-align: center;
  white-space: nowrap;
  user-select: none;
  line-height: 1;
  text-decoration: none;
  -webkit-tap-highlight-color: transparent;
}
.btn:hover  { transform: translateY(-2px); }
.btn:active { transform: translateY(0) scale(0.975); }
.btn:disabled, .btn[aria-disabled="true"] { opacity: 0.45; cursor: not-allowed; pointer-events: none; }

.btn-primary { background: var(--primary); color: #fff; border-color: var(--primary); }
.btn-primary:hover { opacity: 0.87; box-shadow: 0 8px 28px rgba(0,0,0,0.2); }

.btn-outline { background: transparent; color: var(--primary); border-color: var(--primary); }
.btn-outline:hover { background: var(--primary); color: #fff; }

.btn-ghost {
  background: rgba(255,255,255,0.1);
  color: #fff;
  border-color: rgba(255,255,255,0.25);
}
.btn-ghost:hover { background: rgba(255,255,255,0.2); }

.btn-accent { background: var(--accent); color: #0f172a; border-color: var(--accent); }
.btn-accent:hover { filter: brightness(1.08); }

/* ============================================================
   NAVIGATION
   ============================================================ */
.navbar {
  position: sticky;
  top: 0;
  z-index: 100;
  background: var(--dark);
  border-bottom: 1px solid rgba(255,255,255,0.07);
  transition: box-shadow var(--ease);
}
.navbar.scrolled { box-shadow: 0 4px 40px rgba(0,0,0,0.45); }

.navbar-inner {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: var(--space-sm) var(--space-md);
  max-width: var(--max-width);
  margin: 0 auto;
  gap: var(--space-md);
}
.navbar-logo {
  font-family: var(--font-heading);
  font-size: 1.2rem;
  font-weight: 800;
  color: #fff;
  letter-spacing: -0.3px;
  max-width: clamp(120px, 42%, 260px);
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
  flex-shrink: 0;
}
.navbar-links {
  display: flex;
  gap: 28px;
  align-items: center;
  flex: 1;
  justify-content: center;
}
.navbar-links a {
  color: rgba(255,255,255,0.68);
  font-size: 0.875rem;
  font-weight: 500;
  transition: color var(--ease);
  white-space: nowrap;
}
.navbar-links a:hover { color: #fff; }

.navbar-right {
  display: flex;
  align-items: center;
  gap: var(--space-sm);
  flex-shrink: 0;
}
.navbar-cta {
  padding: 9px 20px;
  background: var(--primary);
  color: #fff;
  border-radius: 9px;
  font-size: 0.875rem;
  font-weight: 700;
  transition: opacity var(--ease), transform var(--ease);
  white-space: nowrap;
}
.navbar-cta:hover { opacity: 0.84; transform: translateY(-1px); color: #fff; }

/* ---- Hamburger Toggle ---- */
.nav-toggle {
  display: none;
  flex-direction: column;
  justify-content: center;
  align-items: center;
  gap: 5px;
  width: 40px;
  height: 40px;
  background: rgba(255,255,255,0.07);
  border: 1px solid rgba(255,255,255,0.14);
  border-radius: 8px;
  cursor: pointer;
  padding: 0;
  flex-shrink: 0;
  transition: background var(--ease);
}
.nav-toggle:hover { background: rgba(255,255,255,0.13); }
.nav-toggle span {
  display: block;
  width: 18px;
  height: 2px;
  background: rgba(255,255,255,0.9);
  border-radius: 2px;
  transition: transform 0.3s ease, opacity 0.3s ease, width 0.3s ease;
  transform-origin: center;
}
.nav-toggle[aria-expanded="true"] span:nth-child(1) { transform: translateY(7px) rotate(45deg); }
.nav-toggle[aria-expanded="true"] span:nth-child(2) { opacity: 0; width: 0; }
.nav-toggle[aria-expanded="true"] span:nth-child(3) { transform: translateY(-7px) rotate(-45deg); }

/* ---- Mobile Nav Overlay ---- */
.nav-overlay {
  position: fixed;
  inset: 0;
  background: rgba(0,0,0,0.62);
  z-index: 150;
  opacity: 0;
  pointer-events: none;
  transition: opacity 0.3s ease;
  -webkit-backdrop-filter: blur(2px);
  backdrop-filter: blur(2px);
}
.nav-overlay.open { opacity: 1; pointer-events: all; }

/* ---- Mobile Nav Panel ---- */
.nav-mobile {
  position: fixed;
  top: 0;
  right: 0;
  bottom: 0;
  width: min(300px, 85vw);
  background: var(--dark);
  z-index: 200;
  transform: translateX(100%);
  transition: transform 0.35s cubic-bezier(0.4, 0, 0.2, 1);
  display: flex;
  flex-direction: column;
  padding: var(--space-md);
  border-left: 1px solid rgba(255,255,255,0.08);
  overflow-y: auto;
  -webkit-overflow-scrolling: touch;
}
.nav-mobile.open { transform: translateX(0); }

.nav-mobile-header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  margin-bottom: var(--space-lg);
  padding-bottom: var(--space-sm);
  border-bottom: 1px solid rgba(255,255,255,0.07);
}
.nav-mobile-logo { font-family: var(--font-heading); font-weight: 800; color: #fff; font-size: 1.05rem; }
.nav-mobile-close {
  width: 34px;
  height: 34px;
  background: rgba(255,255,255,0.07);
  border: 1px solid rgba(255,255,255,0.12);
  border-radius: 8px;
  color: rgba(255,255,255,0.75);
  font-size: 1.1rem;
  cursor: pointer;
  display: flex;
  align-items: center;
  justify-content: center;
  transition: background var(--ease), color var(--ease);
  line-height: 1;
}
.nav-mobile-close:hover { background: rgba(255,255,255,0.14); color: #fff; }

.nav-mobile-links { display: flex; flex-direction: column; gap: 2px; flex: 1; }
.nav-mobile-links a {
  display: block;
  color: rgba(255,255,255,0.72);
  font-size: 1rem;
  font-weight: 600;
  padding: 13px var(--space-sm);
  border-radius: 9px;
  transition: background var(--ease), color var(--ease);
}
.nav-mobile-links a:hover { background: rgba(255,255,255,0.08); color: #fff; }
.nav-mobile-links a + a { border-top: 1px solid rgba(255,255,255,0.05); }

.nav-mobile-cta {
  margin-top: var(--space-lg);
  padding-top: var(--space-md);
  border-top: 1px solid rgba(255,255,255,0.07);
}
.nav-mobile-cta .btn { width: 100%; justify-content: center; }

/* ============================================================
   HERO
   ============================================================ */
.hero {
  background: linear-gradient(140deg, var(--dark) 0%, color-mix(in srgb, var(--dark) 50%, var(--primary)) 100%);
  padding: var(--space-2xl) var(--space-md) var(--space-xl);
  position: relative;
  overflow: hidden;
}
.hero::before {
  content: '';
  position: absolute;
  inset: 0;
  background:
    radial-gradient(ellipse at 18% 62%, rgba(255,255,255,0.04) 0%, transparent 55%),
    radial-gradient(ellipse at 85% 14%, rgba(255,255,255,0.05) 0%, transparent 48%);
  pointer-events: none;
}
.hero-inner {
  position: relative;
  z-index: 1;
  display: grid;
  grid-template-columns: 1fr 1fr;
  gap: var(--space-xl);
  align-items: center;
  max-width: var(--max-width);
  margin: 0 auto;
}
.hero-badge {
  display: inline-block;
  padding: 5px 14px;
  border-radius: 100px;
  background: rgba(255,255,255,0.1);
  border: 1px solid rgba(255,255,255,0.18);
  color: rgba(255,255,255,0.88);
  font-size: 0.7rem;
  font-weight: 700;
  text-transform: uppercase;
  letter-spacing: 0.1em;
  margin-bottom: var(--space-sm);
}
.hero h1 {
  color: #fff;
  margin-bottom: var(--space-sm);
}
.hero-sub {
  font-size: clamp(1rem, 2vw, 1.125rem);
  color: rgba(255,255,255,0.68);
  line-height: 1.75;
  margin-bottom: var(--space-lg);
  max-width: 460px;
}
.hero-actions {
  display: flex;
  gap: var(--space-sm);
  flex-wrap: wrap;
  margin-bottom: var(--space-md);
}
.hero-trust {
  display: flex;
  align-items: center;
  gap: 10px;
  color: rgba(255,255,255,0.52);
  font-size: 0.83rem;
}
.hero-trust strong { color: rgba(255,255,255,0.86); }

/* Hero stat cards */
.hero-visual { display: flex; flex-direction: column; gap: var(--space-sm); }
.hero-card {
  background: rgba(255,255,255,0.08);
  border: 1px solid rgba(255,255,255,0.13);
  border-radius: var(--radius-lg);
  padding: var(--space-sm) var(--space-md);
  display: flex;
  align-items: center;
  gap: var(--space-sm);
  -webkit-backdrop-filter: blur(12px);
  backdrop-filter: blur(12px);
  transition: background var(--ease);
}
.hero-card:hover { background: rgba(255,255,255,0.12); }
.hero-card-offset {
  margin-left: 36px;
  max-width: calc(100% - 36px);
}
.hero-card-icon {
  width: 46px;
  height: 46px;
  border-radius: 11px;
  background: var(--primary);
  display: flex;
  align-items: center;
  justify-content: center;
  font-size: 1.25rem;
  flex-shrink: 0;
}
.hero-card-icon.green { background: #10b981; }
.hero-card-val   { font-size: 1.45rem; font-weight: 800; color: #fff; line-height: 1.1; }
.hero-card-label { font-size: 0.75rem; color: rgba(255,255,255,0.55); margin-top: 2px; }

/* ============================================================
   FEATURES
   ============================================================ */
.features {
  padding: var(--space-xl) var(--space-md);
  background: var(--light);
}
.features-grid {
  display: grid;
  grid-template-columns: repeat(3, 1fr);
  gap: var(--space-md);
  max-width: var(--max-width);
  margin: 0 auto;
  align-items: stretch;
}
.feature-card {
  background: #fff;
  border-radius: var(--radius-lg);
  padding: var(--space-lg) var(--space-md);
  border: 1px solid rgba(0,0,0,0.05);
  box-shadow: var(--shadow);
  display: flex;
  flex-direction: column;
  gap: var(--space-xs);
  height: 100%;
  transition: box-shadow 0.28s ease, transform 0.28s ease;
  position: relative;
  overflow: hidden;
}
.feature-card::after {
  content: '';
  position: absolute;
  top: 0;
  left: 0;
  right: 0;
  height: 3px;
  background: var(--primary);
  opacity: 0;
  transition: opacity 0.28s ease;
}
.feature-card:hover { box-shadow: var(--shadow-lg); transform: translateY(-5px); }
.feature-card:hover::after { opacity: 1; }

.feature-icon-wrap {
  width: 50px;
  height: 50px;
  border-radius: 13px;
  background: var(--light);
  display: flex;
  align-items: center;
  justify-content: center;
  font-size: 1.5rem;
  margin-bottom: var(--space-xs);
  flex-shrink: 0;
}
.feature-card h3 { color: #0f172a; }
.feature-card p {
  font-size: 0.875rem;
  color: #64748b;
  line-height: 1.7;
  flex: 1;
  margin-top: 4px;
}
.feature-link {
  font-size: 0.82rem;
  font-weight: 700;
  color: var(--primary);
  margin-top: 6px;
  display: inline-flex;
  align-items: center;
  gap: 4px;
  transition: gap var(--ease);
}
.feature-link:hover { gap: 8px; }

/* ============================================================
   ABOUT
   ============================================================ */
.about { padding: var(--space-xl) var(--space-md); background: #fff; }
.about-inner {
  display: grid;
  grid-template-columns: 1fr 1fr;
  gap: var(--space-xl);
  align-items: center;
  max-width: var(--max-width);
  margin: 0 auto;
}
.about-visual {
  border-radius: var(--radius-lg);
  background: linear-gradient(135deg, var(--light) 0%, color-mix(in srgb, var(--light) 35%, var(--primary)) 100%);
  aspect-ratio: 4 / 3;
  display: flex;
  align-items: center;
  justify-content: center;
  font-size: 6rem;
  position: relative;
  overflow: hidden;
}
.about-badge {
  position: absolute;
  bottom: var(--space-sm);
  right: var(--space-sm);
  background: var(--primary);
  color: #fff;
  padding: 6px 14px;
  border-radius: 9px;
  font-size: 0.78rem;
  font-weight: 700;
}
.about-content { display: flex; flex-direction: column; gap: var(--space-sm); }
.about-content h2 { margin-bottom: 4px; }
.about-content > p { color: #64748b; line-height: 1.8; }
.about-stats {
  display: flex;
  flex-wrap: wrap;
  gap: 20px 32px;
  padding-top: var(--space-md);
  border-top: 1px solid #e2e8f0;
  margin-top: var(--space-xs);
}
.stat-value {
  display: block;
  font-family: var(--font-heading);
  font-size: 1.9rem;
  font-weight: 800;
  color: var(--primary);
  line-height: 1.1;
}
.stat-label {
  font-size: 0.76rem;
  color: #94a3b8;
  font-weight: 500;
  margin-top: 4px;
  display: block;
}

/* ============================================================
   TESTIMONIALS
   ============================================================ */
.testimonials { padding: var(--space-xl) var(--space-md); background: var(--light); }
.testimonials-grid {
  display: grid;
  grid-template-columns: repeat(3, 1fr);
  gap: var(--space-md);
  max-width: var(--max-width);
  margin: 0 auto;
  align-items: stretch;
}
.testimonial-card {
  background: #fff;
  border-radius: var(--radius-lg);
  padding: var(--space-lg) var(--space-md);
  border: 1px solid rgba(0,0,0,0.05);
  box-shadow: var(--shadow);
  display: flex;
  flex-direction: column;
  gap: var(--space-sm);
  height: 100%;
  transition: box-shadow 0.28s ease, transform 0.28s ease;
}
.testimonial-card:hover { box-shadow: var(--shadow-lg); transform: translateY(-4px); }
.testimonial-stars { color: #f59e0b; letter-spacing: 3px; font-size: 0.88rem; }
.testimonial-text {
  font-size: 0.9rem;
  color: #374151;
  line-height: 1.8;
  font-style: italic;
  flex: 1;
}
.testimonial-author { display: flex; align-items: center; gap: var(--space-sm); margin-top: auto; }
.testimonial-avatar {
  width: 42px;
  height: 42px;
  border-radius: 50%;
  display: flex;
  align-items: center;
  justify-content: center;
  font-weight: 700;
  font-size: 0.85rem;
  color: #fff;
  flex-shrink: 0;
}
.testimonial-name { font-size: 0.875rem; font-weight: 700; color: #0f172a; }
.testimonial-role { font-size: 0.77rem; color: #94a3b8; margin-top: 2px; }

/* ============================================================
   FAQ
   ============================================================ */
.faq { padding: var(--space-xl) var(--space-md); background: #fff; }
.faq-inner { max-width: 760px; margin: 0 auto; }
.faq-list { display: flex; flex-direction: column; gap: 10px; }
.faq-item { border: 1px solid #e2e8f0; border-radius: var(--radius); overflow: hidden; transition: border-color var(--ease); }
.faq-item.open { border-color: var(--primary); }
.faq-question {
  width: 100%;
  display: flex;
  justify-content: space-between;
  align-items: center;
  gap: var(--space-sm);
  padding: 18px var(--space-md);
  background: none;
  border: none;
  cursor: pointer;
  font-size: 0.9375rem;
  font-weight: 600;
  color: #0f172a;
  text-align: left;
  transition: background var(--ease);
}
.faq-question:hover { background: var(--light); }
.faq-icon {
  font-size: 1.35rem;
  font-weight: 300;
  color: var(--primary);
  flex-shrink: 0;
  line-height: 1;
  transition: transform 0.25s ease;
}
.faq-item.open .faq-icon { transform: rotate(45deg); }
.faq-answer { display: none; padding: 0 var(--space-md) var(--space-md); }
.faq-item.open .faq-answer { display: block; }
.faq-answer p { font-size: 0.9rem; color: #64748b; line-height: 1.8; }

/* ============================================================
   CONTACT
   ============================================================ */
.contact {
  padding: var(--space-xl) var(--space-md);
  background: linear-gradient(140deg, #0f172a 0%, #1e293b 100%);
  text-align: center;
}
.contact-inner { max-width: 600px; margin: 0 auto; }
.contact .section-label { color: var(--accent); }
.contact h2 { color: #fff; margin-bottom: var(--space-sm); }
.contact-sub { color: rgba(255,255,255,0.6); line-height: 1.75; margin-bottom: var(--space-lg); }
.contact-cta {
  display: inline-flex;
  align-items: center;
  gap: 8px;
  padding: 16px 40px;
  background: var(--primary);
  color: #fff;
  border-radius: var(--radius);
  font-weight: 700;
  font-size: 1rem;
  margin-bottom: var(--space-lg);
  transition: opacity var(--ease), transform var(--ease), box-shadow var(--ease);
}
.contact-cta:hover { opacity: 0.87; transform: translateY(-2px); color: #fff; box-shadow: 0 12px 32px rgba(0,0,0,0.3); }
.contact-details { display: flex; gap: var(--space-lg); justify-content: center; flex-wrap: wrap; }
.contact-item { display: flex; align-items: center; gap: 9px; color: rgba(255,255,255,0.65); font-size: 0.9rem; }

/* ============================================================
   FOOTER
   ============================================================ */
.footer {
  background: var(--dark);
  padding: var(--space-md) var(--space-md);
  border-top: 1px solid rgba(255,255,255,0.05);
}
.footer-inner {
  display: flex;
  align-items: center;
  justify-content: space-between;
  flex-wrap: wrap;
  gap: var(--space-sm);
  max-width: var(--max-width);
  margin: 0 auto;
}
.footer-logo    { font-family: var(--font-heading); font-weight: 800; color: #fff; font-size: 1.05rem; }
.footer-tagline { color: rgba(255,255,255,0.42); font-size: 0.85rem; }
.footer-copy    { color: rgba(255,255,255,0.28); font-size: 0.78rem; }

/* ============================================================
   ANIMATIONS
   ============================================================ */
@keyframes fadeUp {
  from { opacity: 0; transform: translateY(22px); }
  to   { opacity: 1; transform: none; }
}
@keyframes scaleIn {
  from { opacity: 0; transform: scale(0.92); }
  to   { opacity: 1; transform: none; }
}
.reveal {
  opacity: 0;
  transform: translateY(22px);
  transition: opacity 0.55s ease, transform 0.55s ease;
}
.reveal.visible { opacity: 1; transform: none; }

/* ============================================================
   RESPONSIVE — 1024px (large tablet)
   ============================================================ */
@media (max-width: 1024px) {
  .features-grid     { grid-template-columns: repeat(2, 1fr); }
  .testimonials-grid { grid-template-columns: repeat(2, 1fr); }
}

/* ============================================================
   RESPONSIVE — 768px (tablet)
   ============================================================ */
@media (max-width: 768px) {
  .navbar-links,
  .navbar-cta      { display: none; }
  .nav-toggle      { display: flex; }

  .hero            { padding: var(--space-xl) var(--space-sm) var(--space-lg); overflow-x: hidden; }
  .hero-inner      { grid-template-columns: 1fr; gap: var(--space-lg); }
  .hero-visual     { display: none; }
  .hero-sub        { max-width: 100%; }

  .about-inner     { grid-template-columns: 1fr; gap: var(--space-lg); }
  .about-visual    { max-width: 100%; }

  .features        { padding: var(--space-lg) var(--space-sm); }
  .features-grid   { grid-template-columns: 1fr; }

  .testimonials    { padding: var(--space-lg) var(--space-sm); }
  .testimonials-grid { grid-template-columns: 1fr; }

  .faq             { padding: var(--space-lg) var(--space-sm); }
  .about           { padding: var(--space-lg) var(--space-sm); }
  .contact         { padding: var(--space-lg) var(--space-sm); }
  .footer          { padding: var(--space-sm); }

  .about-stats     { gap: var(--space-sm) var(--space-md); }
  .contact-details { flex-wrap: wrap; justify-content: center; }
  .footer-inner    { flex-wrap: wrap; gap: 8px; }
  .section-header  { margin-bottom: var(--space-md); }
}

/* ============================================================
   RESPONSIVE — 480px (mobile)
   ============================================================ */
@media (max-width: 480px) {
  :root {
    --space-lg:  36px;
    --space-xl:  60px;
    --space-2xl: 80px;
  }
  .hero            { padding: var(--space-lg) var(--space-sm); }
  .hero-actions    { flex-direction: column; align-items: stretch; }
  .hero-actions .btn { width: 100%; justify-content: center; }
  .hero-sub        { font-size: 1rem; }
  .navbar-inner    { padding: 12px var(--space-sm); }

  .about-stats > div { flex: 1 1 calc(50% - var(--space-sm)); }
  .contact-details   { flex-direction: column; align-items: center; gap: var(--space-sm); }
  .footer-inner      { flex-direction: column; text-align: center; gap: 8px; }

  .feature-card,
  .testimonial-card  { padding: var(--space-md) var(--space-sm); }
  .features-grid,
  .testimonials-grid { gap: var(--space-sm); }

  .faq-question      { padding: 15px var(--space-sm); font-size: 0.9rem; }
  .faq-answer        { padding: 0 var(--space-sm) var(--space-sm); }
}`;
  },

  /* ----------------------------------------------------------
     JS — mobile nav, FAQ, scroll reveal, smooth scroll
  ---------------------------------------------------------- */
  generateJS() {
    return `/* =============================================
   MockupAI — Generated JavaScript
   ============================================= */
(function () {
  'use strict';

  /* ---- Navbar scroll shadow ---- */
  var navbar = document.querySelector('.navbar');
  if (navbar) {
    window.addEventListener('scroll', function () {
      navbar.classList.toggle('scrolled', window.scrollY > 20);
    }, { passive: true });
  }

  /* ---- Mobile Navigation ---- */
  var navToggle  = document.querySelector('.nav-toggle');
  var navMobile  = document.querySelector('.nav-mobile');
  var navOverlay = document.querySelector('.nav-overlay');
  var navClose   = document.querySelector('.nav-mobile-close');

  function openNav() {
    if (!navMobile) return;
    navToggle && navToggle.setAttribute('aria-expanded', 'true');
    navMobile.classList.add('open');
    navOverlay && navOverlay.classList.add('open');
    document.body.style.overflow = 'hidden';
  }
  function closeNav() {
    if (!navMobile) return;
    navToggle && navToggle.setAttribute('aria-expanded', 'false');
    navMobile.classList.remove('open');
    navOverlay && navOverlay.classList.remove('open');
    document.body.style.overflow = '';
  }

  navToggle  && navToggle.addEventListener('click', function () {
    navToggle.getAttribute('aria-expanded') === 'true' ? closeNav() : openNav();
  });
  navOverlay && navOverlay.addEventListener('click', closeNav);
  navClose   && navClose.addEventListener('click', closeNav);

  /* Close mobile nav on any link click inside it */
  navMobile && navMobile.querySelectorAll('a').forEach(function (a) {
    a.addEventListener('click', closeNav);
  });

  /* Close on Escape */
  document.addEventListener('keydown', function (e) {
    if (e.key === 'Escape') closeNav();
  });

  /* ---- FAQ Accordion ---- */
  document.querySelectorAll('.faq-question').forEach(function (btn) {
    btn.addEventListener('click', function () {
      var item   = btn.closest('.faq-item');
      var isOpen = item.classList.contains('open');
      document.querySelectorAll('.faq-item.open').forEach(function (el) {
        el.classList.remove('open');
        el.querySelector('.faq-question').setAttribute('aria-expanded', 'false');
      });
      if (!isOpen) {
        item.classList.add('open');
        btn.setAttribute('aria-expanded', 'true');
      }
    });
  });

  /* ---- Smooth scroll for anchor links ---- */
  document.querySelectorAll('a[href^="#"]').forEach(function (a) {
    a.addEventListener('click', function (e) {
      var id = this.getAttribute('href');
      if (id === '#') return;
      var target = document.querySelector(id);
      if (target) {
        e.preventDefault();
        target.scrollIntoView({ behavior: 'smooth', block: 'start' });
      }
    });
  });

  /* ---- Scroll reveal with staggered delays ---- */
  if ('IntersectionObserver' in window) {
    var cards = document.querySelectorAll(
      '.feature-card, .testimonial-card, .faq-item, .hero-card, .about-inner, .stat-value'
    );
    cards.forEach(function (el, i) {
      el.classList.add('reveal');
      /* stagger siblings within same grid row */
      el.style.transitionDelay = (i % 3) * 0.08 + 's';
    });
    var observer = new IntersectionObserver(function (entries) {
      entries.forEach(function (entry) {
        if (entry.isIntersecting) {
          entry.target.classList.add('visible');
          observer.unobserve(entry.target);
        }
      });
    }, { threshold: 0.1, rootMargin: '0px 0px -32px 0px' });
    cards.forEach(function (el) { observer.observe(el); });
  }

}());`;
  },

  /* ----------------------------------------------------------
     HTML — for ZIP export (external CSS + JS files)
  ---------------------------------------------------------- */
  generateHTML(data, css, js) {
    const p = data.colorPalette || {};
    const headingFont = (data.typography?.heading || 'Inter').replace(/['"]/g, '');
    const bodyFont    = (data.typography?.body    || 'Inter').replace(/['"]/g, '');
    const fonts = [...new Set([headingFont, bodyFont])]
      .map(f => `family=${f.replace(/ /g, '+')}:wght@400;500;600;700;800`)
      .join('&');

    const navLinks = Array.isArray(data.navbar?.links)
      ? data.navbar.links.map(l => `<li><a href="#${this._slug(l)}">${this._esc(l)}</a></li>`).join('\n          ')
      : '';
    const mobileNavLinks = Array.isArray(data.navbar?.links)
      ? data.navbar.links.map(l => `<a href="#${this._slug(l)}">${this._esc(l)}</a>`).join('\n          ')
      : '';

    const features = this._buildFeatures(data);
    const testimonials = this._buildTestimonials(data, p);
    const faqItems = this._buildFAQ(data);
    const stats = this._buildStats(data);

    return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${this._esc(data.seoMeta?.title || data.businessName)}</title>
  <meta name="description" content="${this._esc(data.seoMeta?.description || '')}">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?${fonts}&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="css/styles.css">
</head>
<body>

  <nav class="navbar" role="navigation" aria-label="Main navigation">
    <div class="navbar-inner">
      <a href="#" class="navbar-logo">${this._esc(data.navbar?.logo || data.businessName)}</a>
      <ul class="navbar-links" role="list">
        ${navLinks}
      </ul>
      <div class="navbar-right">
        <a href="#contact" class="navbar-cta">${this._esc(data.hero?.ctaPrimary || 'Get Started')}</a>
        <button class="nav-toggle" aria-label="Open navigation menu" aria-expanded="false" aria-controls="nav-mobile">
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
        </button>
      </div>
    </div>
  </nav>

  <div class="nav-overlay" id="nav-overlay" aria-hidden="true"></div>
  <div class="nav-mobile" id="nav-mobile" role="dialog" aria-label="Navigation menu" aria-modal="true">
    <div class="nav-mobile-header">
      <span class="nav-mobile-logo">${this._esc(data.navbar?.logo || data.businessName)}</span>
      <button class="nav-mobile-close" aria-label="Close navigation menu">✕</button>
    </div>
    <nav class="nav-mobile-links" aria-label="Mobile navigation">
      ${mobileNavLinks}
    </nav>
    <div class="nav-mobile-cta">
      <a href="#contact" class="btn btn-primary">${this._esc(data.hero?.ctaPrimary || 'Get Started')}</a>
    </div>
  </div>

  <section class="hero" id="hero" aria-label="Hero">
    <div class="hero-inner">
      <div class="hero-text">
        <div class="hero-badge">${this._esc(data.industry)}</div>
        <h1>${this._esc(data.hero?.headline)}</h1>
        <p class="hero-sub">${this._esc(data.hero?.subheadline)}</p>
        <div class="hero-actions">
          <a href="#contact" class="btn btn-primary">${this._esc(data.hero?.ctaPrimary)}</a>
          <a href="#about"   class="btn btn-ghost">${this._esc(data.hero?.ctaSecondary)}</a>
        </div>
        <div class="hero-trust">
          <span aria-hidden="true">⭐⭐⭐⭐⭐</span>
          <span>${this._esc(data.hero?.socialProof || '')}</span>
        </div>
      </div>
      <div class="hero-visual" aria-hidden="true">
        <div class="hero-card">
          <div class="hero-card-icon">📈</div>
          <div><div class="hero-card-val">+147%</div><div class="hero-card-label">Growth this quarter</div></div>
        </div>
        <div class="hero-card hero-card-offset">
          <div class="hero-card-icon green">✓</div>
          <div><div class="hero-card-val">98%</div><div class="hero-card-label">Customer satisfaction</div></div>
        </div>
      </div>
    </div>
  </section>

  <section class="features" id="features" aria-label="Features">
    <div class="section-header">
      <span class="section-label">What We Offer</span>
      <h2 class="section-heading">Everything You Need to Succeed</h2>
      <p class="section-sub">Powerful capabilities designed to help your business thrive.</p>
    </div>
    <div class="features-grid">
      ${features}
    </div>
  </section>

  <section class="about" id="about" aria-label="About us">
    <div class="about-inner">
      <div class="about-visual" aria-hidden="true">
        <span>🏢</span>
        <div class="about-badge">Est. 2024</div>
      </div>
      <div class="about-content">
        <span class="section-label">Our Story</span>
        <h2>${this._esc(data.about?.heading)}</h2>
        <p>${this._esc(data.about?.body)}</p>
        <a href="#contact" class="btn btn-primary" style="align-self:flex-start">${this._esc(data.hero?.ctaPrimary)}</a>
        <div class="about-stats">
          ${stats}
        </div>
      </div>
    </div>
  </section>

  <section class="testimonials" id="testimonials" aria-label="Testimonials">
    <div class="section-header">
      <span class="section-label">Testimonials</span>
      <h2 class="section-heading">What Our Clients Say</h2>
      <p class="section-sub">Real stories from real people who chose ${this._esc(data.businessName)}.</p>
    </div>
    <div class="testimonials-grid">
      ${testimonials}
    </div>
  </section>

  <section class="faq" id="faq" aria-label="Frequently asked questions">
    <div class="faq-inner">
      <div class="section-header">
        <span class="section-label">FAQ</span>
        <h2 class="section-heading">Questions? We've got answers.</h2>
      </div>
      <div class="faq-list" role="list">
        ${faqItems}
      </div>
    </div>
  </section>

  <section class="contact" id="contact" aria-label="Contact">
    <div class="contact-inner">
      <span class="section-label">${this._esc(data.contact?.heading)}</span>
      <h2>${this._esc(data.contact?.heading)}</h2>
      <p class="contact-sub">${this._esc(data.contact?.subtext)}</p>
      <a href="mailto:${this._esc(data.contact?.email)}" class="contact-cta">
        Send Us a Message
      </a>
      <div class="contact-details">
        <div class="contact-item">
          <span aria-hidden="true">📧</span>
          <span>${this._esc(data.contact?.email)}</span>
        </div>
        <div class="contact-item">
          <span aria-hidden="true">📞</span>
          <span>${this._esc(data.contact?.phone)}</span>
        </div>
      </div>
    </div>
  </section>

  <footer class="footer" role="contentinfo">
    <div class="footer-inner">
      <div class="footer-logo">${this._esc(data.businessName)}</div>
      <div class="footer-tagline">${this._esc(data.footer?.tagline)}</div>
      <div class="footer-copy">© ${data.footer?.year || new Date().getFullYear()} ${this._esc(data.businessName)}. All rights reserved.</div>
    </div>
  </footer>

  <script src="js/main.js"></script>
</body>
</html>`;
  },

  /* ----------------------------------------------------------
     Preview HTML — CSS + JS inlined for iframe
  ---------------------------------------------------------- */
  generatePreviewHTML(data) {
    const css = this.generateCSS(data);
    const js  = this.generateJS();
    const p   = data.colorPalette || {};
    const headingFont = (data.typography?.heading || 'Inter').replace(/['"]/g, '');
    const bodyFont    = (data.typography?.body    || 'Inter').replace(/['"]/g, '');
    const fonts = [...new Set([headingFont, bodyFont])]
      .map(f => `family=${f.replace(/ /g, '+')}:wght@400;500;600;700;800`)
      .join('&');

    const navLinks = Array.isArray(data.navbar?.links)
      ? data.navbar.links.map(l => `<li><a href="#${this._slug(l)}">${this._esc(l)}</a></li>`).join('\n          ')
      : '';
    const mobileNavLinks = Array.isArray(data.navbar?.links)
      ? data.navbar.links.map(l => `<a href="#${this._slug(l)}">${this._esc(l)}</a>`).join('\n        ')
      : '';

    const features    = this._buildFeatures(data);
    const testimonials = this._buildTestimonials(data, p);
    const faqItems    = this._buildFAQ(data);
    const stats       = this._buildStats(data);

    return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${this._esc(data.seoMeta?.title || data.businessName)}</title>
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?${fonts}&display=swap" rel="stylesheet">
  <style>${css}</style>
</head>
<body>
  <nav class="navbar">
    <div class="navbar-inner">
      <a href="#" class="navbar-logo">${this._esc(data.navbar?.logo || data.businessName)}</a>
      <ul class="navbar-links">
        ${navLinks}
      </ul>
      <div class="navbar-right">
        <a href="#contact" class="navbar-cta">${this._esc(data.hero?.ctaPrimary || 'Get Started')}</a>
        <button class="nav-toggle" aria-label="Open menu" aria-expanded="false">
          <span></span><span></span><span></span>
        </button>
      </div>
    </div>
  </nav>

  <div class="nav-overlay"></div>
  <div class="nav-mobile">
    <div class="nav-mobile-header">
      <span class="nav-mobile-logo">${this._esc(data.navbar?.logo || data.businessName)}</span>
      <button class="nav-mobile-close">✕</button>
    </div>
    <nav class="nav-mobile-links">
      ${mobileNavLinks}
    </nav>
    <div class="nav-mobile-cta">
      <a href="#contact" class="btn btn-primary">${this._esc(data.hero?.ctaPrimary || 'Get Started')}</a>
    </div>
  </div>

  <section class="hero" id="hero">
    <div class="hero-inner">
      <div class="hero-text">
        <div class="hero-badge">${this._esc(data.industry)}</div>
        <h1>${this._esc(data.hero?.headline)}</h1>
        <p class="hero-sub">${this._esc(data.hero?.subheadline)}</p>
        <div class="hero-actions">
          <a href="#contact" class="btn btn-primary">${this._esc(data.hero?.ctaPrimary)}</a>
          <a href="#about" class="btn btn-ghost">${this._esc(data.hero?.ctaSecondary)}</a>
        </div>
        <div class="hero-trust">
          <span>⭐⭐⭐⭐⭐</span>
          <span>${this._esc(data.hero?.socialProof || '')}</span>
        </div>
      </div>
      <div class="hero-visual">
        <div class="hero-card">
          <div class="hero-card-icon">📈</div>
          <div><div class="hero-card-val">+147%</div><div class="hero-card-label">Growth this quarter</div></div>
        </div>
        <div class="hero-card hero-card-offset">
          <div class="hero-card-icon green">✓</div>
          <div><div class="hero-card-val">98%</div><div class="hero-card-label">Customer satisfaction</div></div>
        </div>
      </div>
    </div>
  </section>

  <section class="features" id="features">
    <div class="section-header">
      <span class="section-label">What We Offer</span>
      <h2 class="section-heading">Everything You Need to Succeed</h2>
      <p class="section-sub">Powerful capabilities designed to help your business thrive.</p>
    </div>
    <div class="features-grid">${features}</div>
  </section>

  <section class="about" id="about">
    <div class="about-inner">
      <div class="about-visual"><span>🏢</span><div class="about-badge">Est. 2024</div></div>
      <div class="about-content">
        <span class="section-label">Our Story</span>
        <h2>${this._esc(data.about?.heading)}</h2>
        <p>${this._esc(data.about?.body)}</p>
        <a href="#contact" class="btn btn-primary" style="align-self:flex-start">${this._esc(data.hero?.ctaPrimary)}</a>
        <div class="about-stats">${stats}</div>
      </div>
    </div>
  </section>

  <section class="testimonials" id="testimonials">
    <div class="section-header">
      <span class="section-label">Testimonials</span>
      <h2 class="section-heading">What Our Clients Say</h2>
      <p class="section-sub">Real stories from real people who chose ${this._esc(data.businessName)}.</p>
    </div>
    <div class="testimonials-grid">${testimonials}</div>
  </section>

  <section class="faq" id="faq">
    <div class="faq-inner">
      <div class="section-header">
        <span class="section-label">FAQ</span>
        <h2 class="section-heading">Questions? We've got answers.</h2>
      </div>
      <div class="faq-list">${faqItems}</div>
    </div>
  </section>

  <section class="contact" id="contact">
    <div class="contact-inner">
      <span class="section-label">${this._esc(data.contact?.heading)}</span>
      <h2>${this._esc(data.contact?.heading)}</h2>
      <p class="contact-sub">${this._esc(data.contact?.subtext)}</p>
      <a href="mailto:${this._esc(data.contact?.email)}" class="contact-cta">Send Us a Message</a>
      <div class="contact-details">
        <div class="contact-item"><span>📧</span><span>${this._esc(data.contact?.email)}</span></div>
        <div class="contact-item"><span>📞</span><span>${this._esc(data.contact?.phone)}</span></div>
      </div>
    </div>
  </section>

  <footer class="footer">
    <div class="footer-inner">
      <div class="footer-logo">${this._esc(data.businessName)}</div>
      <div class="footer-tagline">${this._esc(data.footer?.tagline)}</div>
      <div class="footer-copy">© ${data.footer?.year || new Date().getFullYear()} ${this._esc(data.businessName)}. All rights reserved.</div>
    </div>
  </footer>

  <script>${js}</script>
</body>
</html>`;
  },

  /* ----------------------------------------------------------
     Shared HTML builders (used by both export + preview)
  ---------------------------------------------------------- */
  _buildFeatures(data) {
    if (!Array.isArray(data.features)) return '';
    return data.features.map(f => `
        <article class="feature-card">
          <div class="feature-icon-wrap">${f.icon || '✦'}</div>
          <h3>${this._esc(f.title)}</h3>
          <p>${this._esc(f.description)}</p>
          <a href="#contact" class="feature-link">Learn more →</a>
        </article>`).join('');
  },

  _buildTestimonials(data, p) {
    if (!Array.isArray(data.testimonials)) return '';
    const colors = [p.primary || '#6366f1', '#10b981', '#f59e0b'];
    return data.testimonials.map((t, i) => {
      const initials = (t.avatar && t.avatar.length <= 3)
        ? t.avatar
        : (t.name || 'U').split(' ').map(w => w[0]).join('').substring(0, 2).toUpperCase();
      return `
        <article class="testimonial-card">
          <div class="testimonial-stars">★★★★★</div>
          <p class="testimonial-text">"${this._esc(t.text)}"</p>
          <div class="testimonial-author">
            <div class="testimonial-avatar" style="background:${colors[i % 3]}">${initials}</div>
            <div>
              <div class="testimonial-name">${this._esc(t.name)}</div>
              <div class="testimonial-role">${this._esc(t.role)}</div>
            </div>
          </div>
        </article>`;
    }).join('');
  },

  _buildFAQ(data) {
    if (!Array.isArray(data.faq)) return '';
    return data.faq.map(item => `
        <div class="faq-item">
          <button class="faq-question" aria-expanded="false">
            <span>${this._esc(item.q)}</span>
            <span class="faq-icon" aria-hidden="true">+</span>
          </button>
          <div class="faq-answer" role="region">
            <p>${this._esc(item.a)}</p>
          </div>
        </div>`).join('');
  },

  _buildStats(data) {
    const stats = [data.about?.highlightStat1, data.about?.highlightStat2, data.about?.highlightStat3].filter(Boolean);
    return stats.map(s => `
              <div>
                <span class="stat-value">${this._esc(s.value)}</span>
                <span class="stat-label">${this._esc(s.label)}</span>
              </div>`).join('');
  },

  /* Escape HTML special characters */
  _esc(str) {
    if (!str) return '';
    return String(str)
      .replace(/&/g, '&amp;')
      .replace(/</g, '&lt;')
      .replace(/>/g, '&gt;')
      .replace(/"/g, '&quot;');
  },

  /* Slugify a nav link label for anchor IDs */
  _slug(str) {
    if (!str) return '';
    return String(str).toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
  },
};
